# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.6629, 0.0709, 0.9959, 0.4573, 0.1478, 0.2962, 0.2129],
        [0.9963, 0.7443, 0.2260, 0.0130, 0.1581, 0.0543, 0.7659],
        [0.4399, 0.4748, 0.8008, 0.9698, 0.4239, 0.2502, 0.4509],
        [0.3077, 0.8752, 0.4528, 0.3545, 0.3614, 0.5839, 0.4610],
        [0.4110, 0.3233, 0.6175, 0.1413, 0.8278, 0.2628, 0.7920],
        [0.7501, 0.8434, 0.3925, 0.3546, 0.1210, 0.8610, 0.3092],
        [0.0855, 0.5222, 0.8808, 0.7134, 0.0257, 0.0014, 0.5414]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
random_tensor2 = torch.rand(1, 7)
random_tensor2

# Perform matrix multiplication
torch.matmul(random_tensor, random_tensor2.T)

tensor([[0.8598],
        [0.8869],
        [1.1141],
        [0.8659],
        [0.7988],
        [0.9853],
        [0.7828]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)

# Create two random tensors
random_tensor3 = torch.rand(7, 7)
random_tensor4 = torch.rand(1, 7)

# Matrix multiply tensors
torch.matmul(random_tensor3, random_tensor4.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# Set random seed
RANDOM_SEED = 1234
torch.manual_seed(seed = RANDOM_SEED)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [9]:
# Perform matmul on tensor_A and tensor_B
output = torch.matmul(tensor_A, tensor_B.T)
output, output.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [11]:
# Find max
torch.max(output)

# Find min
torch.min(output)

tensor(0.3647, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [13]:
# Find arg max
output.argmax()

# Find arg min
output.argmin()

tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [15]:
# Set seed
RADOM_SEED = 7
torch.manual_seed(seed = RANDOM_SEED)

# Create random tensor
random_tensor5 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
random_tensor6 = random_tensor5.squeeze()

# Print out tensors and their shapes
random_tensor5, random_tensor5.shape, random_tensor6, random_tensor6.shape


(tensor([[[[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681,
            0.6738, 0.3315]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681, 0.6738,
         0.3315]),
 torch.Size([10]))